name: Deploy

on:
  push:
    branches:
      - master

jobs:

  deploy:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1.x

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build and test
      run: ./build.sh

    - name: Deploy
      run: |
        git config --global user.email 'njlr@users.noreply.github.com'
        git config --global user.name 'njlr'
        git fetch --prune --unshallow
        cp -r ./out /tmp/docs
        git checkout -b gh-pages
        git branch --set-upstream-to=origin/gh-pages
        git pull
        ls -A1 | xargs rm -rf
        cp -r /tmp/docs/. ./
        git add .
        git commit -m "Updates pages"
        git push
